### ISSUE TITLE
Provide a "soft fail" when the response is not in json format

### ISSUE THREAD

**Issue by erikyo** [wp-blocks/wp-blocks#23]
I happened to enter a wrong target and I get an error like below:

```bash
Unable to fetch "https://github.com/WordPress/gutenberg/raw/release/16.0/package.json"
undefined:7
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 6
    at JSON.parse (<anonymous>)
...
```

I think it is due to the fact that it is assumed that the response is in a json format when in this case it is not 

https://github.com/wp-blocks/wp-blocks/blob/60c102c703d08486023595a01a145ef79d945235/packages/wp-update/src/index.ts#L126-L128

To avoid the issue the `Json.parse` could be wrapped up with try catch, or @johnhooks do you think there might be better solutions?

**Comment by johnhooks** [comment]
A try/catch is the right solution. Catch the error, check  `error instanceof SyntaxError`, if so, assume the release was not found and provide a helpful message and call `process.exit(1)`. If it's not a `SyntaxError`, rethrow.

**Comment by johnhooks** [comment]
@erikyo another option is to check the status code of the response, that is probably an even better solution for this situation, because GitHub is responding with a 404 with a body of HTML. And that is why the parse fails. Handling both situations is the right thing todo.

**Comment by erikyo** [comment]
Yep! The status code seems more correct, good catch! Something like below could fit? A different response has to be returned in case that it isn't a syntax error?

```js
async function fetchJsonFile(url) {
    const response = await fetch(url);
    const text = await response.text();
    if ( response.status < 300 ) try {
      return JSON.parse(text);
    } catch (error) {
      if (error instanceof SyntaxError)
        console.log(`It seems that the url is wrong "${url}"`);
    }
    process.exit(1)
}
```
